### ISSUE TITLE
zsl.createShielding throws error

### ISSUE THREAD

**Issue by realcodywburns** [jpmorganchase/zsl-q#1]
zsl_geth1.6  build

After `result = zsl.createShielding(rho, pk, value)`

```
Error: EOF
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:10
```

from 1.log
````
geth: ./libsnark/src/algebra/fields/fp.tcc:485: libsnark::Fp_model<n, modulus>& libsnark::Fp_model<n, modulus>::operator-=(const libsnark::Fp_model<n, modulus>&) [with long int n = 4l; const libsnark::bigint<n>& modulus = ((const libsnark::bigint<4l>&)(& libsnark::alt_bn

128_modulus_q))]: Assertion `borrow == 0' failed.
SIGABRT: abort
PC=0x7f9b25d06428 m=7
signal arrived during cgo execution
````

**Comment by realcodywburns** [comment]
rebuilt with zsl_geth1.5

````
Error: Invalid JSON RPC response: {"error":{"EOF":"EOF","code":-32603},"id":19,"version":"2.0"}
    at web3.js:3122:20
    at web3.js:6026:15
    at web3.js:4998:36
    at <anonymous>:1:10
````
same error in log

**Comment by bitcartel** [comment]
Do you have the zsl-q-params parameter files installed in the current directory?

**Comment by realcodywburns** [comment]
yes they are in the 7nodes dir

**Comment by realcodywburns** [comment]
So, I the .vk and .pk that were in the 7node folders were truncated. I downloaded from zsl-q-params inside of the vm and verified that the checksums did not match. once I rm'ed the old files I was able to get `test_zslprecompile.js` to pass all tests

marking resolved......
